Add apt wrapper to avoid race conditions while using apt/dpkg
Some cloud images may lock apt/dpkg lock files because they can run
automated upgrades cron jobs (f.e. scripts like
/usr/bin/unattended-upgrades) at the same time when cloud-init executes
user-data script which in turn tries to update apt cache, then install
reclass, salt-master packages, but fails.

It is proposed to use apt wrapper function instead which will wait until
apt/dpkg lock files become unlocked and execute apt-get command then
(or fail if waiting timeout expired).

Change-Id: I853af148622d9d9d386053892462403b0a8accb5

diff --git a/template/_server_instance_single.yaml b/template/_server_instance_single.yaml
--- a/template/_server_instance_single.yaml
+++ b/template/_server_instance_single.yaml
@@ -63,12 +63,35 @@ resources:
             # Redirect all outputs
             exec > >(tee -i /tmp/mk-bootstrap.log) 2>&1
             set -x
+
+            # Add wrapper to apt-get to avoid race conditions
+            # with cron jobs running 'unattended-upgrades' script
+            aptget_wrapper() {
+              local apt_wrapper_timeout=300
+              local start_time=$(date '+%s')
+              local fin_time=$((start_time + apt_wrapper_timeout))
+              while true; do
+                if (( "$(date '+%s')" > fin_time )); then
+                  echo "aptget_wrapper - ERROR: Timeout exceeded: ${apt_wrapper_timeout} s. Lock files are still not released. Terminating..."
+                  exit 1
+                fi
+                if fuser /var/lib/apt/lists/lock >/dev/null 2>&1 || fuser /var/lib/dpkg/lock >/dev/null 2>&1; then
+                  echo "aptget_wrapper - INFO: Waiting while another apt/dpkg process releases locks..."
+                  sleep 30
+                  continue
+                else
+                  apt-get $@
+                  break
+                fi
+              done
+            }
+
             echo "Preparing base OS ..."
             echo "nameserver 172.18.208.44" >> /etc/resolv.conf
             echo "nameserver 8.8.8.8" >> /etc/resolv.conf
             case "$node_os" in
                 trusty)
-                    which wget > /dev/null || (apt-get update; apt-get install -y wget)
+                    which wget > /dev/null || (aptget_wrapper update; aptget_wrapper install -y wget)
 
                     echo "deb [arch=amd64] http://apt-mk.mirantis.com/trusty nightly salt extra" > /etc/apt/sources.list.d/mcp_salt.list
                     wget -O - http://apt-mk.mirantis.com/public.gpg | apt-key add -
@@ -76,13 +99,13 @@ resources:
                     echo "deb http://repo.saltstack.com/apt/ubuntu/14.04/amd64/2016.3 trusty main" > /etc/apt/sources.list.d/saltstack.list
                     wget -O - https://repo.saltstack.com/apt/ubuntu/14.04/amd64/2016.3/SALTSTACK-GPG-KEY.pub | apt-key add -
 
-                    apt-get clean
-                    apt-get update
-                    apt-get install -y salt-common
-                    apt-get install -y salt-minion
+                    aptget_wrapper clean
+                    aptget_wrapper update
+                    aptget_wrapper install -y salt-common
+                    aptget_wrapper install -y salt-minion
                     ;;
                 xenial)
-                    which wget > /dev/null || (apt-get update; apt-get install -y wget)
+                    which wget > /dev/null || (aptget_wrapper update; aptget_wrapper install -y wget)
 
                     echo "deb [arch=amd64] http://apt-mk.mirantis.com/xenial nightly salt extra" > /etc/apt/sources.list.d/mcp_salt.list
                     wget -O - http://apt-mk.mirantis.com/public.gpg | apt-key add -
@@ -90,9 +113,9 @@ resources:
                     echo "deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/2016.3 xenial main" > /etc/apt/sources.list.d/saltstack.list
                     wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/2016.3/SALTSTACK-GPG-KEY.pub | apt-key add -
 
-                    apt-get clean
-                    apt-get update
-                    apt-get install -y salt-minion
+                    aptget_wrapper clean
+                    aptget_wrapper update
+                    aptget_wrapper install -y salt-minion
                     ;;
                 *)
                     echo "OS not known"
